spring:
  profiles:
    active: @profiles.active@
  application:
    name: MyAdmin

# 日志
logging:
  level:
    cn.daenx.myadmin: @logging.level@
    org.springframework: warn
  config: classpath:logback.xml


#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.daenx.*.domain.po
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型
      # AUTO = 数据库ID自增
      # NONE = 该类型为未设置主键类型
      # INPUT = 用户输入ID
      # ASSIGN_ID = 全局唯一ID (数字类型唯一ID)
      # ASSIGN_UUID = 全局唯一ID (UUID)
      id-type: ASSIGN_UUID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 使用驼峰原模原样对应
    map-underscore-to-camel-case: true
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
