spring:
  profiles:
    active: @profiles.active@
  application:
    name: MyAdmin

# 日志
logging:
  level:
    cn.daenx.myadmin: @logging.level@
    org.springframework: warn
  config: classpath:logback.xml


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: cn.daenx.myadmin.*.po
  global-config:
    id-type: ASSIGN_UUID
    db-column-underline: true
    # 刷新mapper
    refresh-mapper: true
  # sql日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl