spring:
  profiles:
    active: @profiles.active@
  application:
    name: MyAdmin

# ????
logging:
  level:
    cn.daenx.myadmin: @logging.level@
    org.springframework: warn
  config: classpath:logback.xml


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # ???????package?????????
  type-aliases-package: cn.daenx.myadmin.*.po
  global-config:
    # ???? 0=???1=??2=?????3=??ID?4=??UUID
    id-type: 4
    # ???????
    db-column-underline: true
    # ??mapper???xml???????????????????
    refresh-mapper: true
  # ??sql??
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl